azilZaPse/Controllers/PasController.cs
using azilZaPse.Models;
using azilZaPse.Models.Interfejsi;
using azilZaPse.Models.Repository_Ef_Baza;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace azilZaPse.Controllers
{
    public class PasController : Controller
    {
        private IKuceInterface RadnoKuce;

        private AzilZaPseEntities1 azilEntities = new AzilZaPseEntities1();

        public PasController()
        {
            RadnoKuce = new KuceRepository();
        }
        public ActionResult Dodaj()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Dodaj(KuceBO novoKuce)
        {
            if (novoKuce.ProveraValidnosti())
            {
                RadnoKuce.Dodaj(novoKuce);
            }
            ModelState.Clear();
            return View();
        }
        public ActionResult Pregledaj()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Pregledaj(KartonPsaBO kartonPsa)
        {
            if (kartonPsa.ProveraValidnosti())                                     //mozda tehnicki nepotrebno zbog javascript provere ali za svaki slucaj
            {
                RadnoKuce.UpdateKartona(kartonPsa);
            }
            ModelState.Clear();
            return View();
        }

        public ActionResult Udomi()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Udomi(KuceBO kuce)
        {
            RadnoKuce.Udomi(kuce.IdCipa);
            ModelState.Clear();
            return View();
        }
        public ActionResult Trazi()
        {
            return View();
        }

        public ActionResult NadjiKucePoParametrima(int starost, string rasa, string pol)
        {
            if (starost == 0)
                starost = 0;

            if (String.IsNullOrEmpty(rasa))
                rasa = "";

            if (String.IsNullOrEmpty(pol))
                pol = "";

            return PartialView("NadjiKucePoParametrima", RadnoKuce.NadjiKucePoParametrima(starost, rasa, pol));
        }
    }
}

azilZaPse/Controllers/RadnaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace azilZaPse.Controllers
{
    public class RadnaController : Controller
    {
        // GET: Radna
        public ActionResult Index()
        {
            return View();
        }
    }
}

azilZaPse/Views/Pas/Dodaj.cshtml
@model azilZaPse.Models.KuceBO

@{
    ViewBag.Title = "Dodaj";
}


<html>
<body>
    <div class="tekst">
        <form class="form-horizontal" action="@Url.Action("Dodaj", "Pas")" method="post">

            <fieldset>

                <!-- Form Name -->
                <legend>Unos novog psa u azil</legend>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="textinput">ID čipa:</label>
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.IdCipa, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.IdCipa, "", new { @class = "text-danger" })
                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="textinput">Ime:</label>
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.Ime, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Ime, "", new { @class = "text-danger" })
                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="textinput">Rasa:</label>
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.Rasa, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Rasa, "", new { @class = "text-danger" })
                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="numberinput">Starost:</label>
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.Starost, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Starost, "", new { @class = "text-danger" })
                    </div>
                </div>

                <!-- Multiple Radios -->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="radios">Pol:</label>
                    <div class="col-md-4 klasa">
                        @Html.RadioButtonFor(model => model.Pol, "Mužjak")
                        Mužjak
                        @Html.RadioButtonFor(model => model.Pol, "Ženka")
                        Ženka
                    </div>
                    </div>

                @Html.Hidden("UAzilu", "true")

                <!-- Button -->
                <div class="form-group">
                    <label class="col-md-3 control-label text-center" for="singlebutton"></label>
                        <div class="col-md-3">
                            <input type="submit" value="Dodajte novog psa u Azil" class="btn btn-primary" />
                        </div>
                    <div class="col-md-3">
                        <button type ="button" id="back" name="back" class="btn" onclick="location.href='@Url.Action("Index", "Radna")'">Nazad na glavnu stranicu</button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</body>
</html>

<style>
    .tekst {
        width: 50%;
        margin-left: 25%;
        margin-top: 20px;
    }

    legend {
        width: auto;
        margin: 0 auto;
        color: white;
        margin-bottom: 20px;
    }
    .klasa
    {
        padding: 5px;
        padding-left:10px;
    }
</style>

azilZaPse/Views/Pas/NadjiKucePoParametrima.cshtml
@model IEnumerable<azilZaPse.Models.KuceBO>

<table class="table">
    <caption>Rezultati pretrage:</caption>
    <tr>
        <th style="width: 100px;">
            ID čipa:
        </th>
        <th style="width: 100px;">
            Rasa:
        </th>
        <th style="width: 100px;">
            Pol:
        </th>
        <th style="width: 100px;">
            Ime:
        </th>
        <th style="width: 100px;">
            Starost:
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td style="width:20%">
            @Html.DisplayFor(modelItem => item.IdCipa)
        </td>
        <td style="width:20%">
            @Html.DisplayFor(modelItem => item.Rasa)
        </td>
        <td style="width:20%">
            @Html.DisplayFor(modelItem => item.Pol)
        </td>
        <td style="width:20%">
            @Html.DisplayFor(modelItem => item.Ime)
        </td>
        <td style="width:20%">
            @Html.DisplayFor(modelItem => item.Starost)
        </td>
    </tr>
}

</table>
<style>
    caption{
        text-align:center;
        color:white;
    }

     table{
        white-space:normal;
        display: inline-block;
        height: 300px;
        overflow: scroll;
        overflow-x: hidden;
        margin: 0 auto;
        width: 100%;
        border-collapse: collapse;
        table-layout:fixed !important;
    }

    td {
        width: 20%;
        text-align: center;
        border: 1px solid black;
    }
</style>

azilZaPse/Views/Pas/Pregledaj.cshtml
@model azilZaPse.Models.KartonPsaBO

@{
    ViewBag.Title = "Pregledaj";
}

<html>
<body>
    <div class="tekst">
        <form class="form-horizontal" action="@Url.Action("Pregledaj", "Pas")" method="post" onsubmit="return Provera(IdCipa.value, Alergije.value)">

            <fieldset>

                <!-- Form Name -->
                <legend>Izmena podataka u kartonu psa</legend>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="numberinput">ID čipa:</label>
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.IdCipa, new { htmlAttributes = new { @class = "form-control", @id = "IdCipa" } })
                        @Html.ValidationMessageFor(model => model.IdCipa, "", new { @class = "text-danger" })
                    </div>
                </div>
                <!-- Multiple Radios -->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="radios">Da li je vakcinisan protiv besnila?</label>
                    <div id="Vakcina" class="col-md-4">
                        @Html.RadioButtonFor(model => model.DaLiJeVakcinisan, true)
                        Da
                        @Html.RadioButtonFor(model => model.DaLiJeVakcinisan, false, new { @checked = "checked" })
                        Ne
                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="textinput">Alergije:</label>
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.Alergije, new { htmlAttributes = new { @class = "form-control", @id = "Alergije" } })
                        @Html.ValidationMessageFor(model => model.Alergije, "", new { @class = "text-danger" })
                    </div>
                </div>


                <!-- Multiple Radios -->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="radios">Da li je očišćen od parazita?</label>
                    <div id="Paraziti" class="col-md-4">
                        @Html.RadioButtonFor(model => model.OciscenOdParazita, true)
                        Da
                        @Html.RadioButtonFor(model => model.OciscenOdParazita, false, new { @checked = "checked" })
                        Ne
                    </div>
                </div>

                <!-- Button -->
                <div class="form-group">
                    <label class="col-md-3 control-label" for="singlebutton"></label>
                    <div class="col-md-3">
                        <input type="submit" value="Potvrdite izmenu kartona" class="btn btn-primary" />
                    </div>
                    <div class="col-md-3">
                        <button type="button" id="back" name="back" class="btn" onclick="location.href='@Url.Action("Index", "Radna")'">Nazad na glavnu stranicu</button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</body>
</html>

<style>


    legend {
        width: auto;
        margin: 0 auto;
        color: white;
        margin-bottom: 20px;
    }
</style>

<script type="text/javascript">
    function Provera(IdCipa,Alergije) {

        if ((IdCipa == 0) || (Alergije == "")) {
            alert("Molimo unesite sve podatke.");
            alert(IdCipa + Vakcinisan + Alergije + Paraziti);
            return;
        }
    }
</script>

azilZaPse/Views/Pas/Trazi.cshtml
@using azilZaPse.Models.Repository_Ef_Baza

@{
    ViewBag.Title = "Trazi";
}

<html>
<body>
    <div class="tekst">
        <form name="forma" class="form-horizontal" action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">

            <fieldset>

                <!-- Form Name -->
                <legend>Pretraga pasa po kriterijumu</legend>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="textinput">Rasa:</label>
                    <div class="col-md-4">
                        <input id="textinput" name="rasa" type="text" placeholder="Rasa psa" class="form-control input-md" required="">
                    </div>
                </div>

                <!-- Multiple Radios -->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="radios">Pol:</label>
                    <div class="col-md-4">
                        <div class="radio">
                            <label for="radios-0">
                                <input type="radio" name="pol" id="radios-0" value="Mužjak">
                                Mužjak
                            </label>
                        </div>
                        <div class="radio">
                            <label for="radios-1">
                                <input type="radio" name="pol" id="radios-1" value="Ženka">
                                Ženka
                            </label>
                        </div>
                    </div>
                </div>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="numberinput">Starost:</label>
                    <div class="col-md-4">
                        <input id="starost" name="starost" type="number" placeholder="Starost psa" class="form-control input-md" required="">
                    </div>
                </div>
                <!--Text area-->
                <div style="display:flex;justify-content:center;align-items:center;">
                    <div id="SviKucici" style="display:flex;justify-content:center;align-items:center;">
                        @{Html.RenderAction("NadjiKucePoParametrima", "Pas", new { starost = -1, rasa = "", pol = "" });}
                    </div>
                </div>

                <!-- Button -->
                <div class="form-group">
                    <label class="col-md-3 control-label text-center" for="singlebutton"></label>
                    <div class="col-md-3">
                        <button type="button" id="singlebutton" name="singlebutton" class="btn" onclick="pretrazi(starost.value, pol.value, rasa.value)">Pretražite pse</button>
                    </div>
                    <div class="col-md-3">
                        <button type="button" id="back" name="back" class="btn" onclick="location.href='@Url.Action("Index", "Radna")'">Nazad na glavnu stranicu</button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>

</body>
</html>
<style>
    .tekst {
        width: 50%;
        margin-left: 25%;
        margin-top: 20px;
    }

    legend {
        width: auto;
        margin: 0 auto;
        color: white;
        margin-bottom: 20px;
    }

    #SviKucici {
        width: 500px;
    }
</style>

<script type="text/javascript">
    function pretrazi(Starost, Pol, Rasa) {
        var a = document.getElementById("starost").value;
        if (a == "") {
            Starost = 0;
        }

        if ((Starost == 0) && (Pol == "") && (Rasa == "")) {
            alert("Molimo unesite pretragu po barem jednom parametru.");
            return;
        }
        
        $.ajax({
            url: '@Url.Action("NadjiKucePoParametrima", "Pas")',
            data: { starost: Starost, pol: Pol, rasa: Rasa},
            success: function (result) {
                $('#SviKucici').html(result);
            }
        });
    }
</script>

azilZaPse/Views/Pas/Udomi.cshtml
@model azilZaPse.Models.KuceBO

@{
    ViewBag.Title = "Udomi";
}

<html>
<body>
    <div class="tekst">
        <form class="form-horizontal" action="@Url.Action("Udomi", "Pas")" method="post">

            <fieldset>

                <!-- Form Name -->
                <legend>Promenite status psa u azilu</legend>

                <!-- Text input-->
                <div class="form-group">
                    <label class="col-md-4 control-label" for="numberinput">ID čipa:</label>
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.IdCipa, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.IdCipa, "", new { @class = "text-danger" })
                    </div>
                </div>

                <!-- Button -->
                <div class="form-group">
                    <label class="col-md-3 control-label text-center" for="singlebutton"></label>
                    <div class="col-md-3">
                        <button id="singlebutton" name="singlebutton" class="btn btn-primary">Promenite status psa</button>
                    </div>
                    <div class="col-md-3">
                        <button type="button" id="back" name="back" class="btn" onclick="location.href='@Url.Action("Index", "Radna")'">Nazad na glavnu stranicu</button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</body>
</html>

<style>
    .tekst {
        width: 50%;
        margin-left: 25%;
        margin-top: 20px;
    }

    legend {
        width: auto;
        margin: 0 auto;
        color: white;
        margin-bottom: 20px;
    }
</style>