azilZaPse/Controllers/DokumentacijaController.cs
using azilZaPse.Models;
using azilZaPse.Models.Interfejsi;
using azilZaPse.Models.Repository_Ef_Baza;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace azilZaPse.Controllers
{
    public class DokumentacijaController : Controller
    {
        // GET: IzdavanjeDokumentacije
        private IDokumentacijaInterface RadnaDokumentacija;

        public KuceRepository RadnoKuce { get; }

        private AzilZaPseEntities1 azilEntities = new AzilZaPseEntities1();


        public DokumentacijaController()
        {
            RadnaDokumentacija = new DokumentacijaRepository();
            RadnoKuce = new KuceRepository();
        }

        public ActionResult Izdaj()
        {
            ViewBag.Kuce = RadnoKuce.KuciciUAzilu();
            return View();
        }
        [HttpPost]
        public ActionResult Izdaj(DodajDokumentacijuBO NovaDokumentacija)
        {
            NovaDokumentacija.dokumentacija.IdVlasnika = NovaDokumentacija.vlasnik.IdVlasnika;     //Posto imamo samo jedan input za ID ovo kopira id u dokumentaciju
            if (NovaDokumentacija.vlasnik.ProveraValidnosti() && NovaDokumentacija.dokumentacija.ProveraValidnosti())        
            {
                var item = azilEntities.Vlasniks.FirstOrDefault(x => x.idVlasnika == NovaDokumentacija.vlasnik.IdVlasnika);  //Dodati vlasnika samo ako ne postoji
                if (item == null)
                {
                    RadnaDokumentacija.DodajVlasnika(NovaDokumentacija.vlasnik);
                }
                RadnaDokumentacija.DodajDokumentaciju(NovaDokumentacija.dokumentacija);
            }
            ModelState.Clear();
            ViewBag.Kuce = RadnoKuce.KuciciUAzilu();                                                                        //Bez ovoga doda se sve kako treba
            return View();                                                                                                  //ali program puca
        }
        public ActionResult Pretraga()
        {
            return View();
        }

        public ActionResult NadjiDokumentaciju(string idVlasnika)
        {

            return PartialView("NadjiDokumentaciju", RadnaDokumentacija.NadjiDokumentaciju(idVlasnika));
        }
    }
}

azilZaPse/Controllers/PasController.cs
using azilZaPse.Models;
using azilZaPse.Models.Interfejsi;
using azilZaPse.Models.Repository_Ef_Baza;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace azilZaPse.Controllers
{
    public class PasController : Controller
    {
        private IKuceInterface RadnoKuce;

        private AzilZaPseEntities1 azilEntities = new AzilZaPseEntities1();

        public PasController()
        {
            RadnoKuce = new KuceRepository();
        }
        public ActionResult Dodaj()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Dodaj(KuceBO novoKuce)
        {
            if (novoKuce.ProveraValidnosti())
            {
                RadnoKuce.Dodaj(novoKuce);
            }
            ModelState.Clear();
            return View();
        }
        public ActionResult Pregledaj()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Pregledaj(KartonPsaBO kartonPsa)
        {
            if (kartonPsa.ProveraValidnosti())                                     //mozda tehnicki nepotrebno zbog javascript provere ali za svaki slucaj
            {
                RadnoKuce.UpdateKartona(kartonPsa);
            }
            ModelState.Clear();
            return View();
        }

        public ActionResult Udomi()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Udomi(KuceBO kuce)
        {
            RadnoKuce.Udomi(kuce.IdCipa);
            ModelState.Clear();
            return View();
        }
        public ActionResult Trazi()
        {
            return View();
        }

        public ActionResult NadjiKucePoParametrima(int starost, string rasa, string pol)
        {
            if (starost == 0)
                starost = 0;

            if (String.IsNullOrEmpty(rasa))
                rasa = "";

            if (String.IsNullOrEmpty(pol))
                pol = "";

            return PartialView("NadjiKucePoParametrima", RadnoKuce.NadjiKucePoParametrima(starost, rasa, pol));
        }
    }
}

azilZaPse/Controllers/ProizvodController.cs
using azilZaPse.Models;
using azilZaPse.Models.Interfejsi;
using azilZaPse.Models.Repository_Ef_Baza;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace azilZaPse.Views
{
    public class ProizvodController : Controller
    {
        private IProizvodInterface RadniProizvod;

        private AzilZaPseEntities1 azilEntities = new AzilZaPseEntities1();

        public ProizvodController()
        {
            RadniProizvod = new ProizvodiRepository();
        }

        public ActionResult Proveri()
        {
            return View();
        }
        public ActionResult Upravljaj()
        {
            List<ProizvedeniProizvodiBO> trazeni = new List<ProizvedeniProizvodiBO>();
            trazeni = RadniProizvod.NadjiProizvod(7).ToList();
            List<ProizvodjacBO> trazeniProizvodjac = new List<ProizvodjacBO>();
            foreach (ProizvedeniProizvodiBO proizvodjac in trazeni)
            {
                trazeniProizvodjac.Add(proizvodjac.proizvodjac);
            }
            ViewBag.Proizvodjac = trazeniProizvodjac;
            return View();
        }

        public ActionResult PrikazStanja(int Id)
        {
            return PartialView("PrikazStanja", RadniProizvod.NadjiProizvod(Id));
        }

        public ActionResult ProizvodProizvodi(int Id)
        {
            return PartialView("ProizvodProizvodi", RadniProizvod.NadjiProizvod(Id));

        }

        public ActionResult izbrisiProizvod(int Id)
        {
            RadniProizvod.IzbrisiProizvod(Id);
            return new EmptyResult();
        }

        public ActionResult menjajStanjeProizvoda(int idProizvoda, int idProizvodjaca, double kolicina)
        {
            RadniProizvod.menjajStanjeProizvoda(idProizvoda, idProizvodjaca, kolicina);
            return new EmptyResult();
        }
    }
}

azilZaPse/Controllers/RadnaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace azilZaPse.Controllers
{
    public class RadnaController : Controller
    {
        // GET: Radna
        public ActionResult Index()
        {
            return View();
        }
    }
}

azilZaPse/Views/Radna/Index.cshtml
@model azilZaPse.Models.KorisnikBO
@{
    ViewBag.Title = "Index";
}

    <html>
    <body>
            <div class="glavna">
                <h1 align="center">Azil za pse Mrvica</h1>
                <br /><br />
                <div class="container">
                    <div class="row">
                        <div class="col-md-4">
                            <h2 align="center">Rad sa psima</h2>
                        </div>
                        <div class="col-md-4">
                            <h2 align="center">Dokumentacija</h2>
                        </div>
                        <div class="col-md-4">
                            <h2 align="center">Zalihe</h2>
                        </div>
                    </div>
                </div>
                <br /><br />
                <div class="container">
                    <div class="row">
                        <div class="col-md-4">
                            <input type="button" value="Registracija novog psa" onclick="location.href='@Url.Action("Dodaj", "Pas")'">
                        </div>
                        <div class="col-md-4">
                            <input type="button" value="Izdavanje dokumentacije" onclick="location.href='@Url.Action("Izdaj", "Dokumentacija")'">
                        </div>
                        <div class="col-md-4">
                            <input type="button" value="Provera stanja zaliha" onclick="location.href='@Url.Action("Proveri", "Proizvod")'">
                        </div>
                    </div>
                </div>
                <br /><br />
                <div class="container">
                    <div class="row">
                        <div class="col-md-4">
                            <input type="button" value="Pretrazi pse po kriterijumu" onclick="location.href='@Url.Action("Trazi", "Pas")'">
                        </div>
                        <div class="col-md-4">
                            <input type="button" value="Pretraga dokumentacije" onclick="location.href='@Url.Action("Pretraga", "Dokumentacija")'">
                        </div>
                        <div class="col-md-4">
                            <input type="button" value="Upravljanje zalihama" onclick="location.href='@Url.Action("Upravljaj", "Proizvod")'">
                        </div>
                    </div>
                </div>
                <br /><br />
                <div class="container">
                    <div class="row">
                        <div class="col-md-4">
                            <input type="button" value="Izmena kartona psa" onclick="location.href='@Url.Action("Pregledaj", "Pas")'">
                        </div>
                    </div>
                </div>
                <br /><br />
                <div class="container">
                    <div class="row">
                        <div class="col-md-4">
                            <input type="button" value="Izmena statusa psa" onclick="location.href='@Url.Action("Udomi", "Pas")'">
                        </div>
                    </div>
                </div>
                <br /><br />
            </div>
    </body>
</html>

<style>
    input[type=button] {
        margin: 0 auto;
        color: black;
        width: 200px;
        border-radius: 10px;
        background-color: #008CBA;
        padding: 0px;
        border: 0px;
        height: 30px;
        font-family: sans-serif;
        color: white;
    }

    .col-md-4 {
        text-align: center;
    }

    h1 {
        padding-top: 20px;
    }

    .glavna {
        background-color: rgba(0,0,0,0.5);
        color: white;
    }
</style>